version: '3'
services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    volumes:
     - .:/var/www/html
    environment:
      PHP_OPTIONS: "-d memory_limit=-1"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: db_srb_new
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    image: phpmyadmin:latest
    links:
      - mysql:db
    ports:
      - "8082:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: admin@123

volumes:
  docker-mount:
  db-data:
